ported template version of adsf-plugin-template from previous project

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,53 +1,15 @@
 #!/usr/bin/env bash
 
-set -e
-set -o pipefail
+set -euo pipefail
 
-ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
-[ -n "$ASDF_INSTALL_VERSION" ] || (>&2 echo 'Missing ASDF_INSTALL_VERSION' && exit 1)
-[ -n "$ASDF_INSTALL_PATH" ] || (>&2 echo 'Missing ASDF_INSTALL_PATH' && exit 1)
+current_script_path=${BASH_SOURCE[0]}
+plugin_dir=$(dirname "$(dirname "$current_script_path")")
 
-install_kubectl() {
-  local install_type=$1
-  local version=$2
-  local install_path=$3
-  local bin_install_path="$install_path/bin"
-  local download_url="$(get_download_url $version)"
+# shellcheck source=../lib/utils.bash
+source "${plugin_dir}/lib/utils.bash"
 
-  mkdir -p "${bin_install_path}"
+[ -z "${ASDF_INSTALL_TYPE+x}" ] && echo "ASDF_INSTALL_TYPE is required" && exit 1
+[ -z "${ASDF_INSTALL_VERSION+x}" ] && echo "ASDF_INSTALL_VERSION is required" && exit 1
+[ -z "${ASDF_INSTALL_PATH+x}" ] && echo "ASDF_INSTALL_PATH is required" && exit 1
 
-  local bin_path="${bin_install_path}/kubectl"
-  echo "Downloading kubectl from ${download_url}"
-  if curl -L -sf "$download_url" -o "$bin_path"; then
-    chmod +x $bin_path
-  else
-    exit 1
-  fi
-}
-
-get_arch() {
-  uname | tr '[:upper:]' '[:lower:]'
-}
-
-get_cpu() {
-  local machine_hardware_name
-  machine_hardware_name=${ASDF_KUBECTL_OVERWRITE_ARCH:-"$(uname -m)"}
-
-  case "$machine_hardware_name" in
-    'x86_64') local cpu_type="amd64";;
-    'powerpc64le' | 'ppc64le') local cpu_type="ppc64le";;    
-    'aarch64') local cpu_type="arm64";;
-    'armv7l') local cpu_type="arm";;
-    *) local cpu_type="$machine_hardware_name";;
-  esac
-
-  echo "$cpu_type"
-}
-
-get_download_url() {
-  local version="$1"
-  local platform="$(get_arch)"
-  echo "https://dl.k8s.io/release/v${version}/bin/${platform}/$(get_cpu)/kubectl"
-}
-
-install_kubectl $ASDF_INSTALL_TYPE $ASDF_INSTALL_VERSION $ASDF_INSTALL_PATH
+install_version "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
